// frontend/src/Components/Dashboard/New_room.jsx
import { useState, useEffect } from "react";
import axios from "axios";

function NewRoom(props) {
  const [friendList, setFriendList] = useState([]);
  const [listNewRoom, setListNewRoom] = useState([props.username]);
  const [finalMsg, setFinalMsg] = useState("");

  useEffect(() => {
    axios
      .get("http://localhost:4000/getFriends", { withCredentials: true })
      .then((res) => {
        const friends = res.data.friends;
        setFriendList(friends);
      });
  }, []);

  const handleClickFriend = (e) => {
    if (e.target.type !== "checkbox") e.preventDefault();
    let obj;
    if (e.target.className !== "room") obj = e.target.parentNode;
    else obj = e.target;

    let state;
    if (e.target.type !== "checkbox") {
      let checkbox = obj.childNodes[0];
      if (!checkbox.checked) checkbox.checked = true;
      else checkbox.checked = false;
      state = checkbox.checked;
    } else state = e.target.checked;
    if (state) setListNewRoom((oldList) => [...oldList, obj.textContent]);
    else setListNewRoom(listNewRoom.filter((elm) => elm !== obj.textContent));
  };

  const handleNewRoom = (e) => {
    if (listNewRoom.length === 1) return;
    props.socket.emit("new Room", listNewRoom);
  };

  useEffect(() => {
    if (props.socket === null) return;
    props.socket.on("new Room return", (msg) => {
      setFinalMsg(msg);
    });
  }, [props.socket]);

  return (
    <div className="Dialog_box">
      <div className="Container">
        <img
          className="close_button"
          src="/plus.png"
          alt="plus"
          onClick={() => {
            props.setOpenDialogBox(false);
          }}
        ></img>
        Create room by adding your friends :
        <ul>
          {friendList.map((e) => {
            return (
              <li
                className="room"
                key={e._id}
                id={e._id}
                onClick={handleClickFriend}
              >
                <input type="checkbox"></input>
                <img src="/room_image.png" alt="user_image" />
                <span>{e.username}</span>
              </li>
            );
          })}
        </ul>
        <button onClick={handleNewRoom}>Create Room</button>
        {finalMsg}
      </div>
    </div>
  );
}

export default NewRoom;

// frontend/src/Components/Dashboard/Rooms/New_room.svelte
<script>
  import axios from "axios";
  import { socket, username } from "../../../store";

  export let setOpenDialogBox;
  let socketValue;
  socket.subscribe((val) => (socketValue = val));
  let usernameValue;
  username.subscribe((val) => (usernameValue = val));
  let friendList = [];
  let listNewRoom = [usernameValue];
  let finalMsg = "";

  axios
    .get(
      "http://" + process.env.URI + ":" + process.env.API_PORT + "/getFriends",
      { withCredentials: true }
    )
    .then((res) => {
      friendList = res.data.friends;
    });

  function handleClickFriend(e) {
    if (e.target.type !== "checkbox") e.preventDefault();
    let obj;
    if (e.target.className !== "room") obj = e.target.parentNode;
    else obj = e.target;

    let state;
    if (e.target.type !== "checkbox") {
      let checkbox = obj.childNodes[0];
      if (!checkbox.checked) checkbox.checked = true;
      else checkbox.checked = false;
      state = checkbox.checked;
    } else state = e.target.checked;
    if (state) listNewRoom = [...listNewRoom, obj.innerText];
    else listNewRoom = listNewRoom.filter((elm) => elm !== obj.innerText);
  }

  function handleNewRoom(e) {
    if (listNewRoom.length === 1) return;
    socketValue.emit("create Room", listNewRoom);
  }

  socketValue.on("create Room return", (msg) => {
    finalMsg = msg;
  });
</script>

<div class="Dialog_box">
  <div class="Container">
    <img
      class="close_button"
      src="/plus.png"
      alt="plus"
      on:click={() => {
        setOpenDialogBox(false);
      }}
    />
    Create room by adding your friends :
    <ul>
      {#each friendList as friend}
        <li
          class="room"
          key={friend._id}
          id={friend._id}
          on:click={handleClickFriend}
        >
          <input type="checkbox" />
          <img src="/room_image.png" alt="user_image" />
          <span>{friend.username}</span>
        </li>
      {/each}
    </ul>
    <button on:click={handleNewRoom}>Create Room</button>
    {finalMsg}
  </div>
</div>
