// frontend/src/Components/Dashboard.svelte
<script>
  import Room from "./Dashboard/Room.svelte";
  import Messages from "./Dashboard/Messages.svelte";
  import "../styles/Dashboard/Dashboard.css";
  let current_room = "";
  function setCurrentRoom(room) {
    current_room = room;
  }
</script>

<div class="Dashboard">
  <Room {setCurrentRoom} />
  <Messages {current_room} />
</div>

// frontend/src/Components/Dashboard.jsx
import { useState, useEffect } from "react";
import "../styles/Dashboard/Dashboard.css";
import Messages from "./Dashboard/Message";
import Room from "./Dashboard/Room";

function Dashboard(props) {
  const [currentRoom, setCurrentRoom] = useState("");

  return (
    <div className="Dashboard">
      <Room
        username={props.Username}
        socket={props.socket}
        setRoom={setCurrentRoom}
      />
      <Messages
        socket={props.socket}
        currentRoom={currentRoom}
        username={props.Username}
      />
    </div>
  );
}

export default Dashboard;
