// frontend/src/Components/Landing/NavBar.svelte
<script>
  import "../../styles/NavBar/NavBar.css";
  import "../../styles/NavBar/Notification.css";
  import { link } from "svelte-spa-router";
  import { username, socket } from "../../store";
  import axios from "axios";

  let usernameValue;
  username.subscribe((val) => (usernameValue = val));
  let socketValue;
  socket.subscribe((val) => (socketValue = val));
  let notifications = [];
  let notificationsOpen = false;

  $: if (usernameValue !== "")
    axios
      .get(
        "http://" + process.env.URI + ":" + process.env.API_PORT + "/getNotifs",
        {
          params: { username: usernameValue },
          withCredentials: true,
        }
      )
      .then((res) => {
        notifications = res.data;
      });

  function handleAccpetInvit(e) {
    console.log(e);
    socketValue.emit("accept invitation", e);
    notifications = notifications.filter((elm) => elm._id !== e._id);
  }

  const default_routes = [
    { name: "Home", route: "/" },
    { name: "About Us", route: "/about" },
    { name: "Log In", route: "/dashboard" },
    { name: "Sign Up", route: "/register" },
  ];
</script>

<div class="navigation">
  <h2>LOGO</h2>
  {#if usernameValue !== ""}
    <div class="loged">
      <img
        src="/notification.png"
        alt="notif"
        on:click={() => {
          notificationsOpen = !notificationsOpen;
        }}
      />
      <h3>Welcome {usernameValue} !</h3>
      {#if notificationsOpen}
        <div class="Notification">
          {#each notifications as e}
            {#if e.type === "add_friend"}
              <div class="add_friend" key={e._id}>
                <span>{e.message}</span>
                <button
                  on:click={() => {
                    handleAccpetInvit(e);
                  }}
                >
                  ADD
                </button>
                <button>DELETE</button>
              </div>{/if}
          {/each}
        </div>
      {/if}
    </div>
  {:else}
    <ul>
      {#each default_routes as page}
        <li>
          <a use:link href={page.route}>{page.name}</a>
        </li>
      {/each}
    </ul>
  {/if}
</div>

// frontend/src/Components/NavBar.jsx
import { Link } from "react-router-dom";
import "../styles/NavBar/NavBar.css";
import "../styles/NavBar/Notification.css";
import { useEffect, useState } from "react";
import axios from "axios";

function Navbar(props) {
  const [notificationOpen, setNotificationOpen] = useState(false);
  const [notifications, setNotifications] = useState([]);

  useEffect(() => {
    if (props.username === "") return;
    axios
      .get("http://localhost:4000/getNotif", {
        params: { username: props.username },
        withCredentials: true,
      })
      .then((res) => {
        const notifications = res.data;
        setNotifications(notifications);
      });
  }, [props.username]);

  const handleOpenNotif = (e) => {
    setNotificationOpen(!notificationOpen);
  };

  const handleAddFriend = (e) => {
    console.log("test");
    props.socket.emit("accept invitation", e);
    setNotifications(notifications.filter((elm) => elm._id !== e._id));
  };

  if (props.isLogged)
    return (
      <div className="navigation">
        <h2>LOGO</h2>
        <div className="loged">
          <img src="/notification.png" alt="notif" onClick={handleOpenNotif} />
          <h3>Welcome {props.username} !</h3>
          {notificationOpen && (
            <div className="Notification">
              {notifications.map((e) => {
                if (e.type === "add_friend")
                  return (
                    <div className="add_friend" key={e._id}>
                      <span>{e.message}</span>
                      <button
                        onClick={() => {
                          handleAddFriend(e);
                        }}
                      >
                        ADD
                      </button>
                      <button>DELETE</button>
                    </div>
                  );
                return <></>;
              })}
            </div>
          )}
        </div>
      </div>
    );
  else
    return (
      <header className="navigation">
        <h2>LOGO</h2>
        <ul>
          <li>
            <Link to="/">Home</Link>
          </li>
          <li>
            <Link to="/about">About Us</Link>
          </li>
          <li>Contact</li>
          <li>
            <Link to="/dashboard">Log In</Link>
          </li>
        </ul>
      </header>
    );
}

export default Navbar;
