// client/src/Components/Dashboard.jsx
import { useState, useEffect } from "react";
import socketIOClient from "socket.io-client";
import Messages from "./Dashboard/Message";
import Friend from "./Dashboard/Friends";
import Room from "./Dashboard/Room";
import "../styles/Dashboard/Dashboard.css";

function Dashboard(props) {
  const [socket, setSocket] = useState(null);
  const [rooms, setRooms] = useState([]);
  const [currentRoom, setCurrentRoom] = useState("General");

  //create a socket and connect to API
  useEffect(() => {
    setSocket(socketIOClient.connect("http://localhost:4000"));
  }, []);

  return (
    <div className="Dashboard">
      <div className="Menu">
        <Friend />
        <Room />
      </div>
      <Messages
        socket={socket}
        currentRoom={currentRoom}
        username={props.Username}
      />
    </div>
  );
}

export default Dashboard;

// frontend/src/Components/Dashboard/Dashboard.svelte
<script>
  import Room from "./Rooms/Room.svelte";
  import Messages from "./Messages/Messages.svelte";
  import "../../styles/Dashboard/Dashboard.css";
  let current_room = { name: "" };
  function setCurrentRoom(room) {
    current_room = room;
  }
</script>

<div class="Dashboard">
  <Room {setCurrentRoom} />
  <Messages {current_room} />
</div>
