// frontend/src/Components/Dashboard/New_room.jsx
import { useState, useEffect } from "react";
import axios from "axios";

function NewRoom(props) {
  const [friendList, setFriendList] = useState([]);
  const [listNewRoom, setListNewRoom] = useState([props.username]);
  const [finalMsg, setFinalMsg] = useState("");

  useEffect(() => {
    axios
      .get("http://localhost:4000/getFriends", { withCredentials: true })
      .then((res) => {
        const friends = res.data.friends;
        setFriendList(friends);
      });
  }, []);

  const handleClickFriend = (e) => {
    if (e.target.type !== "checkbox") e.preventDefault();
    let obj;
    if (e.target.className !== "room") obj = e.target.parentNode;
    else obj = e.target;

    let state;
    if (e.target.type !== "checkbox") {
      let checkbox = obj.childNodes[0];
      if (!checkbox.checked) checkbox.checked = true;
      else checkbox.checked = false;
      state = checkbox.checked;
    } else state = e.target.checked;
    if (state) setListNewRoom((oldList) => [...oldList, obj.textContent]);
    else setListNewRoom(listNewRoom.filter((elm) => elm !== obj.textContent));
  };

  const handleNewRoom = (e) => {
    if (listNewRoom.length === 1) return;
    props.socket.emit("new Room", listNewRoom);
  };

  useEffect(() => {
    if (props.socket === null) return;
    props.socket.on("new Room return", (msg) => {
      setFinalMsg(msg);
    });
  }, [props.socket]);

  return (
    <div className="Dialog_box">
      <div className="Container">
        <img
          className="close_button"
          src="/plus.png"
          alt="plus"
          onClick={() => {
            props.setOpenDialogBox(false);
          }}
        ></img>
        Create room by adding your friends :
        <ul>
          {friendList.map((e) => {
            return (
              <li
                className="room"
                key={e._id}
                id={e._id}
                onClick={handleClickFriend}
              >
                <input type="checkbox"></input>
                <img src="/room_image.png" alt="user_image" />
                <span>{e.username}</span>
              </li>
            );
          })}
        </ul>
        <button onClick={handleNewRoom}>Create Room</button>
        {finalMsg}
      </div>
    </div>
  );
}

export default NewRoom;

// frontend/src/lib/Components/Dashboard/Rooms/New_room.svelte
<script>
  import axios from "axios";
  import { socket, username } from "../../../store";
  import closeButton from "../../../../assets/icons-pack/close-outline.svg";

  export let setOpenDialogBox;
  let usernameValue;
  username.subscribe((val) => (usernameValue = val));
  let friendList = [];
  let listNewRoom = [usernameValue];
  let finalMsg = "";

  axios
    .get("http://" + window.location.host + "/api/getFriends", {
      withCredentials: true,
    })
    .then((res) => {
      friendList = res.data.friends;
    });

  function handleClickFriend(friend) {
    if (listNewRoom.includes(friend.username)) {
      listNewRoom = listNewRoom.filter((str) => str !== friend.username);
      // @ts-ignore
      document.getElementById(friend._id).checked = false;
    } else {
      listNewRoom.push(friend.username);
      // @ts-ignore
      document.getElementById(friend._id).checked = true;
    }
  }

  function handleNewRoom(e) {
    if (listNewRoom.length === 1) return;
    $socket.emit("Room:create", listNewRoom);
  }

  $socket.on("Room:Create:Return", (msg) => {
    finalMsg = msg;
  });
</script>

<div class="Dialog_box">
  <div class="Container min-w-[300px]">
    <button class="w-12 ml-auto"
      on:click={() => {
        setOpenDialogBox(false);
      }}
    >
      <img
        class="w-12 hover:bg-slate-200 rounded-full"
        src={closeButton}
        alt="close"
      /></button
    >
    New message group :
    <ul class="overflow-y-auto m-3">
      {#each friendList as friend}
        <li
          class="flex hover:bg-slate-400 items-center p-2 border-b-2"
          on:click={() => handleClickFriend(friend)}
          aria-hidden="true"
        >
          <input type="checkbox" id={friend._id} />
          <img
            src="/room_image.png"
            alt="user_image"
            class="h-12 rounded-full"
          />
          <span>{friend.username}</span>
        </li>
      {/each}
    </ul>
    <button
      on:click={handleNewRoom}
      class="text-white bg-blue-500 rounded-full p-1 my-3 hover:bg-slate-500"
      >Create Room</button
    >
    {finalMsg}
  </div>
</div>
