// client/src/Components/Register.jsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import "../styles/login.css";

function Register(props) {
  let navigate = useNavigate();
  const [username, setUsername] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [finalMsg, setFinalMsg] = useState("");

  const handleUsername = (e) => {
    setUsername(e.target.value);
  };

  const verifyUsername = () => {
    if (username === "")
      return (
        <li style={{ color: "#FF4136" }}>Please put a non-empty username</li>
      );
  };

  const handleEmail = (e) => {
    setEmail(e.target.value);
  };

  const validEmail =
    /^(([^<>()[\].,;:\s@"]+(\.[^<>()[\].,;:\s@"]+)*)|(".+"))@(([^<>()[\].,;:\s@"]+\.)+[^<>()[\].,;:\s@"]{2,})$/i;
  const verifyEmail = () => {
    if (!email.match(validEmail))
      return (
        <li style={{ color: "#FF4136" }}>Please put a non-empty username</li>
      );
  };

  const handlePassword = (e) => {
    setPassword(e.target.value);
  };

  const validPassword =
    "^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$";
  const verifyPassword = () => {
    if (!password.match(validPassword))
      return (
        <div style={{ color: "#FF4136" }}>
          <li>At least 8 characters</li>
          <li>One special character</li>
          <li>One uppercase letter</li>
          <li>One lowercase letter</li>
          <li>One number</li>
        </div>
      );
  };

  const handleConfirmPassword = (e) => {
    setConfirmPassword(e.target.value);
  };

  const verifyConfirmPassword = () => {
    if (password !== confirmPassword)
      return <li style={{ color: "#FF4136" }}>Passwords must correspond</li>;
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (
      username === "" ||
      !email.match(validEmail) ||
      !password.match(validPassword) ||
      password !== confirmPassword
    )
      return;
    axios
      .post("http://localhost:4000/register", {
        username: username,
        email: email,
        password: password,
      })
      .then(
        (res) => {
          const msg = res.data.message;
          if (msg === "OK")
            navigate("/login");
          else
            setFinalMsg(msg);
        },
        (error) => {
          setFinalMsg("API not connected");
        }
      );
  };

  return (
    <div className="login">
      <form>
        <h2 className="title">Sign Up</h2>
        Already a member ?
        <a id="sign-up-btn" href="/login">
          Sign In
        </a>
        Username :
        <input
          className="input-field"
          type="text"
          placeholder="Username"
          onChange={handleUsername}
        />
        {verifyUsername()}
        E-mail :
        <input
          className="input-field"
          type="text"
          placeholder="E-mail"
          onChange={handleEmail}
        />
        {verifyEmail()}
        Password :
        <input
          className="input-field"
          type="password"
          placeholder="Password"
          onChange={handlePassword}
        />
        {verifyPassword()}
        Confirm password :
        <input
          className="input-field"
          type="password"
          placeholder="Password"
          onChange={handleConfirmPassword}
        />
        {verifyConfirmPassword()}
        <button type="submit" onClick={handleSubmit}>
          Sign Up !
        </button>
        <h3 style={{ color: "#FF4136" }}>{finalMsg}</h3>
      </form>
    </div>
  );
}

export default Register;

// frontend/src/lib/Components/Landing/Register.svelte
<script>
  import axios from "axios";
  import { push } from "svelte-spa-router";

  let username = "";
  let usernameMsg = "";
  let email = "";
  let emailMsg = "";
  let password = "";
  let passwordMsg = "";
  let confirmPassword = "";
  let confirmPasswordMsg = "";
  let finalMsg = "";

  const validEmail =
    /^(([^<>()[\].,;:\s@"]+(\.[^<>()[\].,;:\s@"]+)*)|(".+"))@(([^<>()[\].,;:\s@"]+\.)+[^<>()[\].,;:\s@"]{2,})$/i;
  function verifyEmail() {
    if (!email.match(validEmail))
      emailMsg =
        '<li style="color: #FF4136">Please put a valid email adress</li>';
    else emailMsg = "";
  }

  const validPassword =
    "^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$";
  function verifyPassword() {
    if (!password.match(validPassword))
      passwordMsg =
        '<div style="color: #FF4136"> \
          <li>At least 8 characters</li> \
          <li>One special character</li> \
          <li>One uppercase letter</li> \
          <li>One lowercase letter</li> \
          <li>One number</li> \
        </div>';
    else passwordMsg = "";
  }

  function verifyConfirmPassword() {
    if (password !== confirmPassword)
      confirmPasswordMsg =
        '<li style="color: #FF4136">Passwords must correspond</li>';
    else confirmPasswordMsg = "";
  }

  function handleSubmit(e) {
    e.preventDefault();

    if (
      username === "" ||
      !email.match(validEmail) ||
      !password.match(validPassword) ||
      password !== confirmPassword
    ) {
      verifyEmail();
      verifyPassword();
      verifyConfirmPassword();
      return;
    }

    axios
      .post("http://" + window.location.host + "/api/register", {
        username: username,
        email: email,
        password: password,
      })
      .then(
        (res) => {
          const msg = res.data.message;
          if (msg === "OK") push("/login");
          else finalMsg = msg;
        },
        (error) => {
          finalMsg = "API not connected";
        }
      );
  }
</script>

<div class="w-full h-full flex items-center justify-center">
  <form
    class="flex flex-col border-2 border-black rounded-xl justify-center text-center p-2 md:text-2xl"
  >
    <h2 class="flex justify-center font-bold text-blue-500 text-3xl p-5">
      Sign Up
    </h2>
    Already a member ?
    <button
      class="text-white bg-blue-500 rounded-full w-fit p-2 mx-auto mb-4 hover:bg-slate-500"
      on:click={() => {
        push("/login");
      }}>Sign In</button
    >
    Username :
    <input
      class="input-field"
      type="text"
      placeholder="Username"
      bind:value={username}
      on:change={() => {
        if (username === "")
          usernameMsg =
            '<li style="color: #FF4136">Please put a non-empty username</li>';
        else usernameMsg = "";
      }}
    />
    {@html usernameMsg}
    E-mail :
    <input
      class="input-field"
      type="text"
      placeholder="E-mail"
      bind:value={email}
      on:change={verifyEmail}
    />
    {@html emailMsg}
    Password :
    <input
      class="input-field"
      type="password"
      placeholder="Password"
      bind:value={password}
      on:change={verifyPassword}
    />
    {@html passwordMsg}
    Confirm password :
    <input
      class="input-field"
      type="password"
      placeholder="Password"
      bind:value={confirmPassword}
      on:change={verifyConfirmPassword}
    />
    {@html confirmPasswordMsg}
    <button
      type="submit"
      class="text-white bg-blue-500 rounded-full p-1 my-3 hover:bg-slate-500"
      on:click={handleSubmit}
    >
      Sign Up !
    </button>
    <h3 style="color: #FF4136">{finalMsg}</h3>
  </form>
</div>
