// client/src/Components/Login.jsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import "../styles/login.css";

function Login(props) {
  let navigate = useNavigate();
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [finalMsg, setFinalMsg] = useState("");

  const handleUsername = (e) => {
    setUsername(e.target.value);
  };

  const handlePassword = (e) => {
    setPassword(e.target.value);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (username === "" || password === "") return;
    axios
      .post("http://localhost:4000/login", {
        username: username,
        password: password,
      }, { withCredentials: true })
      .then(
        (res) => {
          const msg = res.data.message;
          
          if (msg === "OK") navigate("/dashboard");
        },
        (error) => {
          setFinalMsg("API not connected");
        }
      );
  };

  return (
    <div className="login">
      <form>
        <h2 className="title">Sign In</h2>
        <input
          className="input-field"
          type="text"
          placeholder="Username"
          onChange={handleUsername}
        />
        <input
          className="input-field"
          type="password"
          placeholder="Password"
          onChange={handlePassword}
        />
        <button onClick={handleSubmit}>Login</button>
        <h3 style={{ color: "#FF4136" }}>{finalMsg}</h3>
      </form>
      <h3>New here ?</h3>
      <p>Don't hesitate to sign up to access to website !</p>
      <a id="sign-up-btn" href="/register">
        Sign Up
      </a>
    </div>
  );
}

export default Login;

// frontend/src/Components/Landing/Login.svelte
<script>
  import { push } from "svelte-spa-router";
  import axios from "axios";
  export let fetchLogin;

  let username = "";
  let password = "";
  let finalMsg = "";

  function handleSubmit() {
    if (username === "" || password === "") return;
    axios
      .post(
        "http://" + window.location.host + "/api/login",
        {
          username: username,
          password: password,
        },
        { withCredentials: true }
      )
      .then(async (res) => {
        const msg = res.data.message;

        if (msg === "OK") {
          await fetchLogin();
          push("/dashboard");
        } else finalMsg = msg;
      })
      .catch((error) => {
        if (error.response) {
          if (error.response.data === undefined) finalMsg = "Internal Error";
          else finalMsg = error.response.data.message;
        }
      });
  }
</script>

<div class="login">
  <form>
    <h2 class="title">Sign In</h2>
    <input
      class="input-field"
      type="text"
      placeholder="Username"
      on:change={(e) => {
        username = e.target.value;
      }}
    />
    <input
      class="input-field"
      type="password"
      placeholder="Password"
      on:change={(e) => {
        password = e.target.value;
      }}
    />
    <button on:click|preventDefault={handleSubmit}>Login</button>
    <h3 style="color: #FF4136">{finalMsg}</h3>
  </form>
  <h3>New here ?</h3>
  <p>Don't hesitate to sign up to access to website !</p>
  <a id="sign-up-btn" href="/#/register"> Sign Up </a>
</div>
